"""
Base model classes and mixins for SQLAlchemy ORM.

This module provides foundational classes used by all database models:
- Base: Declarative base class for all models
- TimestampMixin: Automatic created_at and updated_at timestamps
- UUIDMixin: UUID primary key with automatic generation
"""
from datetime import datetime
from typing import Any, Dict
import uuid

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy models.
    
    Provides common functionality and serves as the declarative base
    for all database models in the application.
    """
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert model instance to dictionary.
        
        Serializes all mapped columns to a dictionary, handling special types:
        - datetime objects are converted to ISO format strings
        - UUID objects are converted to strings
        - Other types are returned as-is
        
        Returns:
            Dict[str, Any]: Dictionary representation of the model
            
        Example:
            user = User(email="test@example.com", clerk_id="user_123")
            user_dict = user.to_dict()
            # {'id': 'uuid-string', 'email': 'test@example.com', ...}
        """
        result = {}
        for column in self.__table__.columns:
            value = getattr(self, column.name)
            
            # Handle special types for JSON serialization
            if isinstance(value, datetime):
                result[column.name] = value.isoformat()
            elif isinstance(value, uuid.UUID):
                result[column.name] = str(value)
            else:
                result[column.name] = value
                
        return result


class TimestampMixin:
    """
    Mixin that adds automatic timestamp fields to models.
    
    Provides:
    - created_at: Timestamp when record was created (set automatically)
    - updated_at: Timestamp when record was last updated (updated automatically)
    
    Both fields use timezone-aware timestamps and are managed by the database.
    
    Example:
        class User(Base, TimestampMixin):
            __tablename__ = "users"
            id: Mapped[int] = mapped_column(primary_key=True)
            # created_at and updated_at are automatically added
    """
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Timestamp when the record was created"
    )
    
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Timestamp when the record was last updated"
    )


class UUIDMixin:
    """
    Mixin that adds a UUID primary key to models.
    
    Provides:
    - id: UUID primary key with automatic generation using PostgreSQL's gen_random_uuid()
    
    The UUID is generated by the database on insert, ensuring uniqueness
    and avoiding the need for application-level ID generation.
    
    Example:
        class User(Base, UUIDMixin):
            __tablename__ = "users"
            # id field is automatically added as UUID primary key
            email: Mapped[str] = mapped_column(String(255))
    """
    
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="Unique identifier for the record"
    )
